<?php

namespace App\Http\Controllers\Landlord;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Tenant\Manager\RolePermissionsController;
use App\Mail\TenantWelcomeMail;
use App\Models\Landlord\Plan;
use App\Models\Landlord\Tenant;
use App\Models\Tenant\RolePermission;
use App\Models\Tenant\Setting;
use App\Models\Tenant\User;
use App\Services\CloudflareService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Inertia\Inertia;

class TenantController extends Controller
{
    public function index()
    {
        $tenants = Tenant::with('plan', 'domains')
            ->latest()
            ->paginate(15);

        return Inertia::render('Landlord/Tenants/Index', [
            'tenants' => $tenants,
        ]);
    }

    public function create()
    {
        $plans = Plan::where('is_active', true)->get();

        return Inertia::render('Landlord/Tenants/Create', [
            'plans' => $plans,
        ]);
    }

    public function store(Request $request)
    {
        // Computed once up front, so the uniqueness check below validates the
        // exact value that will actually be inserted into domains.domain
        // (e.g. "acme.storelo.pl"), not the bare subdomain ("acme") — the old
        // 'unique:domains,domain' rule checked the wrong column value and
        // essentially never fired, so a colliding subdomain reached
        // domains()->create() and threw an uncaught 500 after the tenant row
        // (and its real database) had already been created.
        $baseDomain = config('tenancy.base_domain') ?: (config('tenancy.central_domains')[0] ?? 'localhost');
        $baseDomain = preg_replace('/:\d+$/', '', $baseDomain); // strip port

        $validated = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'subdomain' => [
                'required', 'string', 'max:255', 'alpha_dash',
                Rule::unique('domains', 'domain')->using(function ($query) use ($baseDomain, $request) {
                    $query->where('domain', $request->input('subdomain') . '.' . $baseDomain);
                }),
            ],
            'plan_id' => ['nullable', 'exists:plans,id'],
            'status' => ['required', 'in:active,suspended'],
            'version' => ['required', 'in:stable,test'],
            'license_ends_at' => ['nullable', 'date'],
            'owner_name' => ['nullable', 'string', 'max:255'],
            'owner_email' => ['nullable', 'email', 'max:255'],
        ]);

        // Create tenant (ID will be auto-generated by stancl/tenancy)
        $tenant = Tenant::create([
            'name' => $validated['name'],
            'subdomain' => $validated['subdomain'],
            'plan_id' => $validated['plan_id'] ?? null,
            'status' => $validated['status'],
            'version' => $validated['version'],
            'license_ends_at' => $validated['license_ends_at'] ?? null,
        ]);

        // Create domain
        $tenant->domains()->create([
            'domain' => $validated['subdomain'] . '.' . $baseDomain,
        ]);

        // Add the DNS record in Cloudflare, when one is configured
        $cloudflare = app(CloudflareService::class);
        if ($cloudflare->isConfigured()) {
            $dnsRecordId = $cloudflare->addSubdomain($validated['subdomain']);
            if ($dnsRecordId) {
                $tenant->update(['data->cloudflare_dns_id' => $dnsRecordId]);
            }
        }

        // Always migrate the tenant database immediately after creation.
        Artisan::call('tenants:migrate', [
            '--tenants' => [$tenant->id],
            '--force' => true,
        ]);

        // Always seed default settings and permissions
        try {
            tenancy()->initialize($tenant);
            $this->seedDefaultRolePermissions();
            $this->seedDefaultSettings($validated['name']);
            tenancy()->end();
        } catch (\Exception $e) {
            Log::error('Failed to seed default settings: ' . $e->getMessage());
            if (tenancy()->initialized) {
                tenancy()->end();
            }
        }

        // Create initial manager account and send welcome email (#23)
        if (!empty($validated['owner_email'])) {
            try {
                $password = Str::random(12);
                $ownerName = $validated['owner_name'] ?? 'Manager';
                $ownerEmail = $validated['owner_email'];

                tenancy()->initialize($tenant);

                User::create([
                    'name' => $ownerName,
                    'email' => $ownerEmail,
                    'password' => Hash::make($password),
                    'role' => 'manager',
                ]);

                tenancy()->end();

                $scheme = app()->environment('production') ? 'https' : 'http';
                $loginUrl = $scheme . '://' . $validated['subdomain'] . '.' . $baseDomain . '/login';

                Mail::to($ownerEmail)->queue(new TenantWelcomeMail(
                    ownerName: $ownerName,
                    shopName: $validated['name'],
                    loginUrl: $loginUrl,
                    password: $password,
                    email: $ownerEmail,
                ));
            } catch (\Exception $e) {
                Log::error('Failed to create tenant manager: ' . $e->getMessage());
                if (tenancy()->initialized) {
                    tenancy()->end();
                }
            }
        }

        $redirect = redirect()->route('landlord.tenants.index')
            ->with('success', "Sklep '{$tenant->name}' został utworzony!");

        if (isset($password)) {
            $redirect = $redirect
                ->with('generated_password', $password)
                ->with('generated_password_email', $validated['owner_email']);
        }

        return $redirect;
    }

    public function show(Tenant $tenant)
    {
        $tenant->load('plan', 'domains');

        return Inertia::render('Landlord/Tenants/Show', [
            'tenant' => $tenant,
        ]);
    }

    public function edit(Tenant $tenant)
    {
        return Inertia::render('Landlord/Tenants/Edit', [
            'tenant' => $tenant->load('plan', 'domains'),
        ]);
    }

    public function update(Request $request, Tenant $tenant)
    {
        $validated = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'plan_id' => ['nullable', 'exists:plans,id'],
            'status' => ['required', 'in:active,suspended'],
            'version' => ['required', 'in:stable,test'],
            'license_ends_at' => ['nullable', 'date'],
        ]);

        $tenant->update($validated);

        return redirect()->route('landlord.tenants.index')
            ->with('success', "Sklep '{$tenant->name}' został zaktualizowany!");
    }

    /**
     * Does NOT drop the database. A real shop's entire database (orders,
     * customers, everything) is too costly to lose to a mis-click, a
     * replayed request, or a compromised super-admin session — this only
     * flags the tenant for deletion. The actual DeleteDatabase pipeline
     * runs later, from the `tenants:prune-pending-deletion` scheduled
     * command, once the grace period in that command has passed. Until
     * then a super-admin can call cancelDeletion() to undo this completely.
     */
    public function destroy(Request $request, Tenant $tenant)
    {
        $request->validate([
            'confirm_name' => ['required', 'string'],
        ]);

        if ($request->confirm_name !== $tenant->name) {
            return back()->withErrors(['confirm_name' => 'Wpisana nazwa nie zgadza się z nazwą sklepu.']);
        }

        $tenant->update([
            'status' => 'pending_deletion',
            'deletion_requested_at' => now(),
        ]);

        return redirect()->route('landlord.tenants.index')
            ->with('success', "Sklep '{$tenant->name}' zostanie trwale usunięty za 7 dni. Możesz to cofnąć do tego czasu.");
    }

    /**
     * Undo a pending deletion (only possible before the grace period elapses
     * and the scheduled prune command has actually dropped the database).
     */
    public function cancelDeletion(Tenant $tenant)
    {
        if ($tenant->status !== 'pending_deletion') {
            return back()->with('error', __('messages.shop_not_marked_for_deletion'));
        }

        $tenant->update([
            'status' => 'active',
            'deletion_requested_at' => null,
        ]);

        return back()->with('success', "Usunięcie sklepu '{$tenant->name}' zostało anulowane.");
    }

    private function seedDefaultSettings(string $shopName): void
    {
        $S = Setting::class;

        $seed = function (string $key, $value, string $type = 'string') use ($S): void {
            if (!$S::has($key)) {
                $S::set($key, $value, $type);
            }
        };

        $seed('shop_name', $shopName);
        $seed('shop_description',
            'Witamy w sklepie ' . htmlspecialchars($shopName, ENT_QUOTES) . '! '
            . 'Oferujemy szeroką gamę produktów w atrakcyjnych cenach. '
            . 'Zamów online — szybko, bezpiecznie i wygodnie.'
        );
        $seed('currency', 'PLN');
        $seed('payment_cash_on_delivery_enabled', false, 'boolean');
        $seed('payment_bank_transfer_enabled', false, 'boolean');
        $seed('payment_online_enabled', false, 'boolean');
        $seed('notification_sound_enabled', true, 'boolean');
        $seed('theme_primary_color', '#4f46e5');
        $seed('theme_font', 'inter');
        $seed('vacation_mode', false, 'boolean');
        $seed('vacation_message', 'Sklep jest chwilowo niedostępny. Zapraszamy wkrótce!');
        $seed('loyalty_enabled', false, 'boolean');
        $seed('loyalty_earn_mode', 'per_pln');
        $seed('loyalty_points_per_pln', 1, 'integer');
        $seed('loyalty_bonus_registration', 50, 'integer');
        $seed('loyalty_bonus_first_order', 100, 'integer');
        $seed('loyalty_bonus_referral', 200, 'integer');
        $seed('low_stock_threshold', 5, 'integer');

        $seed('terms_content', <<<'HTML'
<h1>Regulamin sklepu internetowego</h1>
<p style="color:#6b7280;font-size:0.9em;">Wersja obowiązująca od 1 stycznia 2026 r.</p>

<p><strong>Sprzedawca:</strong> {shop_owner_name}<br>
Nazwa handlowa: {shop_name}<br>
Adres: {shop_address}<br>
E-mail: {shop_email} &nbsp;|&nbsp; Tel.: {shop_phone}<br>
NIP: {shop_nip}</p>

<hr>

<h2>§ 1. Definicje</h2>
<ol>
  <li><strong>Sklep</strong> – sklep internetowy prowadzony przez Sprzedawcę pod adresem dostępnym za pośrednictwem przeglądarki internetowej, umożliwiający zakup produktów.</li>
  <li><strong>Sprzedawca</strong> – {shop_owner_name}, dane wskazane powyżej.</li>
  <li><strong>Klient</strong> – pełnoletnia osoba fizyczna posiadająca pełną zdolność do czynności prawnych, osoba prawna lub jednostka organizacyjna nieposiadająca osobowości prawnej, dokonująca zakupów w Sklepie.</li>
  <li><strong>Konsument</strong> – Klient będący osobą fizyczną dokonujący zakupów w celach niezwiązanych bezpośrednio z działalnością gospodarczą lub zawodową (art. 22¹ Kodeksu cywilnego).</li>
  <li><strong>Zamówienie</strong> – oświadczenie woli Klienta złożone za pośrednictwem Sklepu, stanowiące ofertę zawarcia umowy sprzedaży.</li>
  <li><strong>Umowa</strong> – umowa sprzedaży zawierana na odległość pomiędzy Klientem a Sprzedawcą za pośrednictwem Sklepu.</li>
  <li><strong>Produkt</strong> – rzecz ruchoma lub usługa dostępna w Sklepie, będąca przedmiotem Umowy.</li>
  <li><strong>Koszyk</strong> – element Sklepu, w którym Klient kompletuje wybrane Produkty przed złożeniem Zamówienia.</li>
  <li><strong>Regulamin</strong> – niniejszy dokument.</li>
</ol>

<h2>§ 2. Postanowienia ogólne</h2>
<ol>
  <li>Niniejszy Regulamin określa zasady i warunki korzystania ze Sklepu, składania Zamówień, zawierania Umów oraz tryb postępowania reklamacyjnego.</li>
  <li>Regulamin jest dostępny nieodpłatnie w Sklepie w formie umożliwiającej jego pobranie, utrwalenie i wydrukowanie.</li>
  <li>Korzystanie ze Sklepu jest równoznaczne z zaakceptowaniem postanowień niniejszego Regulaminu.</li>
  <li>Sprzedawca świadczy usługi drogą elektroniczną w rozumieniu ustawy z dnia 18 lipca 2002 r. o świadczeniu usług drogą elektroniczną (Dz.U. 2002 nr 144 poz. 1204 ze zm.).</li>
</ol>

<h2>§ 3. Wymagania techniczne</h2>
<ol>
  <li>Korzystanie ze Sklepu wymaga posiadania urządzenia z dostępem do sieci Internet oraz aktualnej przeglądarki internetowej obsługującej JavaScript i pliki cookies.</li>
  <li>Sprzedawca nie ponosi odpowiedzialności za problemy techniczne wynikające z konfiguracji urządzenia Klienta lub jakości połączenia internetowego.</li>
</ol>

<h2>§ 4. Rejestracja i konto użytkownika</h2>
<ol>
  <li>Klient może dokonywać zakupów bez rejestracji lub założyć Konto, podając dane niezbędne do jego utworzenia.</li>
  <li>Klient zobowiązany jest do podania danych prawdziwych, aktualnych i kompletnych.</li>
  <li>Klient ponosi odpowiedzialność za wszelkie działania podjęte z wykorzystaniem jego Konta.</li>
  <li>Sprzedawca może usunąć Konto lub zawiesić dostęp w przypadku naruszenia Regulaminu.</li>
  <li>Klient może w każdej chwili usunąć swoje Konto. Dane osobowe są anonimizowane zgodnie z Polityką Prywatności, z wyjątkiem danych niezbędnych do realizacji obowiązków prawnych.</li>
</ol>

<h2>§ 5. Składanie zamówień i zawarcie umowy</h2>
<ol>
  <li>Zamówienia można składać za pośrednictwem Sklepu przez całą dobę, 7 dni w tygodniu.</li>
  <li>Złożenie Zamówienia stanowi ofertę Klienta w rozumieniu art. 66 Kodeksu cywilnego. Umowa zostaje zawarta z chwilą przesłania przez Sprzedawcę potwierdzenia przyjęcia Zamówienia do realizacji.</li>
  <li>Potwierdzenie przyjęcia Zamówienia wysyłane jest na adres e-mail Klienta wskazany podczas składania Zamówienia.</li>
  <li>Sprzedawca zastrzega sobie prawo do anulowania Zamówienia w przypadku: podejrzenia nadużycia, niedostępności Produktu w magazynie, niemożności weryfikacji danych Klienta lub awarii systemu płatności. W takim przypadku Klient zostanie niezwłocznie poinformowany, a ewentualne pobrane środki zwrócone.</li>
  <li>Prezentacja Produktów w Sklepie stanowi zaproszenie do zawarcia umowy w rozumieniu art. 71 Kodeksu cywilnego, a nie ofertę w rozumieniu art. 66 Kodeksu cywilnego.</li>
</ol>

<h2>§ 6. Ceny i płatności</h2>
<ol>
  <li>Wszystkie ceny podane w Sklepie są cenami brutto wyrażonymi w złotych polskich (PLN) i zawierają podatek VAT w obowiązującej stawce.</li>
  <li>Koszt dostawy podawany jest odrębnie przed finalizacją Zamówienia i stanowi element łącznej ceny do zapłaty.</li>
  <li>Sprzedawca oferuje następujące metody płatności: płatność elektroniczna (przelew online, BLIK, karta płatnicza), przelew bankowy oraz — jeśli opcja jest aktywna — płatność za pobraniem przy odbiorze.</li>
  <li>W przypadku płatności elektronicznej Klient jest przekierowywany do zewnętrznego operatora płatności. Sprzedawca nie przechowuje danych kart płatniczych Klienta.</li>
  <li>W przypadku płatności przelewem Klient zobowiązany jest do dokonania zapłaty w terminie 3 dni roboczych od złożenia Zamówienia. Po upływie tego terminu Zamówienie może zostać anulowane.</li>
  <li>Sprzedawca zastrzega sobie prawo do zmiany cen Produktów oraz wprowadzania i odwoływania promocji. Zmiany cen nie dotyczą Zamówień już przyjętych do realizacji.</li>
</ol>

<h2>§ 7. Realizacja i dostawa</h2>
<ol>
  <li>Czas realizacji Zamówienia (przygotowanie do wysyłki) wynosi co do zasady 1–3 dni robocze, o ile przy danym Produkcie nie wskazano inaczej.</li>
  <li>Zamówienia złożone w dni robocze do godz. 14:00 przekazywane są do wysyłki tego samego dnia. Zamówienia złożone po godz. 14:00 oraz w weekendy i dni ustawowo wolne od pracy są przekazywane do wysyłki następnego dnia roboczego.</li>
  <li>Dostawa realizowana jest za pośrednictwem firm kurierskich lub do wskazanych punktów odbioru (paczkomaty, punkty Paczki w RUCHu itp.). Dostępne opcje i koszty dostawy prezentowane są w Koszyku przed finalizacją Zamówienia.</li>
  <li>Szacowany czas dostawy od momentu nadania przesyłki wynosi 1–3 dni robocze na terenie Polski. Sprzedawca nie ponosi odpowiedzialności za opóźnienia wynikające z działania przewoźnika, siły wyższej lub błędnego adresu podanego przez Klienta.</li>
  <li>Klient zobowiązany jest do sprawdzenia przesyłki w obecności kuriera. W przypadku stwierdzenia uszkodzeń lub braków zaleca się sporządzenie protokołu szkody, co ułatwi późniejszą reklamację.</li>
  <li>Sprzedawca realizuje dostawy na terenie Rzeczypospolitej Polskiej. Możliwość wysyłki zagranicznej, jeśli jest dostępna, jest wskazana w opisach poszczególnych Produktów.</li>
</ol>

<h2>§ 8. Prawo do odstąpienia od umowy (Konsumenci)</h2>
<ol>
  <li>Konsument ma prawo do odstąpienia od Umowy zawartej na odległość bez podania przyczyny w terminie <strong>14 dni</strong> od daty otrzymania Produktu, na podstawie art. 27 ustawy z dnia 30 maja 2014 r. o prawach konsumenta (Dz.U. 2014 poz. 827 ze zm.).</li>
  <li>Aby skorzystać z prawa do odstąpienia, Konsument powinien poinformować Sprzedawcę o swojej decyzji drogą elektroniczną na adres <strong>{shop_email}</strong> lub pisemnie, wskazując numer Zamówienia oraz numer rachunku bankowego do zwrotu środków.</li>
  <li>Termin do odstąpienia jest zachowany, jeżeli Konsument wyśle oświadczenie przed upływem terminu 14 dni.</li>
  <li>Konsument zobowiązany jest zwrócić Produkt na adres Sprzedawcy niezwłocznie, nie później niż w terminie 14 dni od dnia, w którym odstąpił od Umowy.</li>
  <li>Bezpośrednie koszty zwrotu Produktu ponosi Konsument, o ile Sprzedawca nie postanowił inaczej.</li>
  <li>Sprzedawca zwraca Konsumentowi wszystkie otrzymane płatności, w tym koszty dostawy (z wyjątkiem dodatkowych kosztów wynikających z wybranego przez Konsumenta sposobu dostawy innego niż najtańszy oferowany przez Sprzedawcę), niezwłocznie, nie później niż w terminie 14 dni od dnia otrzymania oświadczenia o odstąpieniu.</li>
  <li>Prawo odstąpienia od umowy nie przysługuje w odniesieniu do Produktów: wyprodukowanych według specyfikacji Konsumenta lub wyraźnie spersonalizowanych; które po dostarczeniu, ze względu na swój charakter, zostają nierozłącznie połączone z innymi rzeczami; z zapieczętowanym opakowaniem, których po otwarciu nie można zwrócić ze względu na ochronę zdrowia lub ze względów higienicznych, jeżeli opakowanie zostało otwarte po dostarczeniu; a także nagrań dźwiękowych, wizualnych lub programów komputerowych dostarczanych w zapieczętowanym opakowaniu, jeżeli opakowanie zostało otwarte po dostarczeniu.</li>
</ol>

<h2>§ 9. Reklamacje i gwarancja</h2>
<ol>
  <li>Sprzedawca ponosi odpowiedzialność za wady fizyczne i prawne Produktów na zasadach określonych w art. 556 i następnych Kodeksu cywilnego (rękojmia).</li>
  <li>Reklamacje należy składać drogą elektroniczną na adres <strong>{shop_email}</strong> lub pisemnie na adres Sprzedawcy: <strong>{shop_address}</strong>.</li>
  <li>Reklamacja powinna zawierać: imię i nazwisko Klienta, numer Zamówienia, datę zakupu, opis stwierdzonej wady oraz żądanie Klienta (naprawa, wymiana, obniżenie ceny, odstąpienie od umowy).</li>
  <li>Sprzedawca rozpatruje reklamacje w terminie 14 dni kalendarzowych od dnia jej otrzymania i informuje Klienta o sposobie jej rozpatrzenia.</li>
  <li>Konsumentowi przysługuje prawo do skorzystania z pozasądowych metod rozpatrywania sporów, w tym mediacji prowadzonej przez właściwe Inspekcje Handlowe lub platformy ODR dostępnej pod adresem <a href="https://ec.europa.eu/consumers/odr" target="_blank">ec.europa.eu/consumers/odr</a>. Więcej informacji na stronie <a href="https://www.uokik.gov.pl" target="_blank">uokik.gov.pl</a>.</li>
</ol>

<h2>§ 10. Ochrona danych osobowych</h2>
<p>Dane osobowe Klientów przetwarzane są zgodnie z Rozporządzeniem Parlamentu Europejskiego i Rady (UE) 2016/679 z dnia 27 kwietnia 2016 r. (RODO) oraz obowiązującymi przepisami krajowymi. Szczegółowe informacje zawiera Polityka Prywatności dostępna w Sklepie.</p>

<h2>§ 11. Własność intelektualna</h2>
<p>Wszelkie treści zamieszczone w Sklepie (grafiki, teksty, logotypy, układ stron) stanowią własność Sprzedawcy lub podmiotów, którym przysługują odpowiednie prawa, i są chronione przepisami prawa autorskiego. Ich kopiowanie, modyfikowanie lub rozpowszechnianie bez zgody Sprzedawcy jest zabronione.</p>

<h2>§ 12. Odpowiedzialność</h2>
<ol>
  <li>Sprzedawca nie ponosi odpowiedzialności za przerwy w funkcjonowaniu Sklepu wynikające z przyczyn technicznych niezależnych od Sprzedawcy, konserwacji lub działania siły wyższej.</li>
  <li>Sprzedawca nie ponosi odpowiedzialności za treści publikowane przez Klientów (np. opinie) niezgodne z rzeczywistością.</li>
  <li>Odpowiedzialność Sprzedawcy wobec Klientów niebędących Konsumentami ograniczona jest do wartości złożonego Zamówienia.</li>
</ol>

<h2>§ 13. Postanowienia końcowe</h2>
<ol>
  <li>W sprawach nieuregulowanych niniejszym Regulaminem zastosowanie mają przepisy prawa polskiego, w szczególności: Kodeksu cywilnego, ustawy o świadczeniu usług drogą elektroniczną, ustawy o prawach konsumenta oraz RODO.</li>
  <li>Wszelkie spory wynikające z korzystania ze Sklepu będą rozstrzygane przez sąd powszechny właściwy miejscowo i rzeczowo dla siedziby Sprzedawcy, z zastrzeżeniem bezwzględnie obowiązujących przepisów dotyczących Konsumentów.</li>
  <li>Sprzedawca zastrzega sobie prawo do zmiany Regulaminu. O zmianach Klienci posiadający Konto zostaną powiadomieni drogą elektroniczną z co najmniej 14-dniowym wyprzedzeniem. Dalsze korzystanie ze Sklepu po wejściu zmian w życie jest równoznaczne z ich akceptacją.</li>
  <li>Niniejszy Regulamin obowiązuje od dnia 1 stycznia 2026 r. i zastępuje wszelkie wcześniejsze wersje.</li>
</ol>
HTML, 'text');
        $seed('privacy_content', <<<'HTML'
<h1>Polityka Prywatności i Ochrony Danych Osobowych</h1>
<p style="color:#6b7280;font-size:0.9em;">Wersja obowiązująca od 1 stycznia 2026 r.</p>

<p>Niniejsza Polityka Prywatności została sporządzona zgodnie z wymogami Rozporządzenia Parlamentu Europejskiego i Rady (UE) 2016/679 z dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych (<strong>RODO</strong>), a także ustawy z dnia 10 maja 2018 r. o ochronie danych osobowych (Dz.U. 2018 poz. 1000 ze zm.).</p>

<hr>

<h2>1. Administrator danych osobowych</h2>
<p>Administratorem Twoich danych osobowych jest:</p>
<p><strong>{shop_owner_name}</strong><br>
Nazwa handlowa: {shop_name}<br>
Adres: {shop_address}<br>
E-mail: {shop_email}<br>
Tel.: {shop_phone}<br>
NIP: {shop_nip}</p>
<p>Administrator nie powołał Inspektora Ochrony Danych. W sprawach dotyczących danych osobowych prosimy o kontakt pod adresem e-mail wskazanym powyżej.</p>

<h2>2. Kategorie przetwarzanych danych osobowych</h2>
<p>W zależności od sposobu korzystania ze Sklepu przetwarzamy następujące kategorie danych:</p>
<table style="width:100%;border-collapse:collapse;font-size:0.9em;">
  <thead>
    <tr style="background:#f3f4f6;">
      <th style="text-align:left;padding:8px;border:1px solid #e5e7eb;">Kategoria</th>
      <th style="text-align:left;padding:8px;border:1px solid #e5e7eb;">Zakres danych</th>
    </tr>
  </thead>
  <tbody>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;">Dane identyfikacyjne</td><td style="padding:8px;border:1px solid #e5e7eb;">imię i nazwisko</td></tr>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;">Dane kontaktowe</td><td style="padding:8px;border:1px solid #e5e7eb;">adres e-mail, numer telefonu</td></tr>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;">Dane adresowe</td><td style="padding:8px;border:1px solid #e5e7eb;">adres dostawy (ulica, numer, kod pocztowy, miejscowość) oraz — opcjonalnie — adres do faktury</td></tr>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;">Dane transakcyjne</td><td style="padding:8px;border:1px solid #e5e7eb;">historia zamówień, wartość zamówień, metoda płatności, numer przesyłki</td></tr>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;">Dane konta</td><td style="padding:8px;border:1px solid #e5e7eb;">adres e-mail, hasło (w formie zaszyfrowanej – hash bcrypt), data rejestracji</td></tr>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;">Dane techniczne</td><td style="padding:8px;border:1px solid #e5e7eb;">adres IP, typ przeglądarki, identyfikatory sesji, pliki cookies</td></tr>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;">Dane opcjonalne</td><td style="padding:8px;border:1px solid #e5e7eb;">data urodzenia (wyłącznie w celu przyznania bonusu urodzinowego – podanie dobrowolne)</td></tr>
  </tbody>
</table>

<h2>3. Cele i podstawy prawne przetwarzania danych</h2>
<table style="width:100%;border-collapse:collapse;font-size:0.9em;">
  <thead>
    <tr style="background:#f3f4f6;">
      <th style="text-align:left;padding:8px;border:1px solid #e5e7eb;">Cel przetwarzania</th>
      <th style="text-align:left;padding:8px;border:1px solid #e5e7eb;">Podstawa prawna (RODO)</th>
    </tr>
  </thead>
  <tbody>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;">Realizacja i obsługa zamówień oraz dostawa</td><td style="padding:8px;border:1px solid #e5e7eb;">art. 6 ust. 1 lit. b – wykonanie umowy</td></tr>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;">Prowadzenie konta użytkownika</td><td style="padding:8px;border:1px solid #e5e7eb;">art. 6 ust. 1 lit. b – wykonanie umowy</td></tr>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;">Obsługa reklamacji, zwrotów i roszczeń</td><td style="padding:8px;border:1px solid #e5e7eb;">art. 6 ust. 1 lit. b – wykonanie umowy; art. 6 ust. 1 lit. f – uzasadniony interes</td></tr>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;">Wypełnienie obowiązków podatkowych i rachunkowych</td><td style="padding:8px;border:1px solid #e5e7eb;">art. 6 ust. 1 lit. c – obowiązek prawny</td></tr>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;">Marketing bezpośredni własnych produktów i usług</td><td style="padding:8px;border:1px solid #e5e7eb;">art. 6 ust. 1 lit. f – uzasadniony interes Administratora</td></tr>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;">Wysyłka newslettera i komunikacji handlowej (za zgodą)</td><td style="padding:8px;border:1px solid #e5e7eb;">art. 6 ust. 1 lit. a – zgoda osoby, której dane dotyczą</td></tr>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;">Zapobieganie nadużyciom i bezpieczeństwo systemu</td><td style="padding:8px;border:1px solid #e5e7eb;">art. 6 ust. 1 lit. f – uzasadniony interes Administratora</td></tr>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;">Statystyki i analiza ruchu (pliki cookies analityczne – za zgodą)</td><td style="padding:8px;border:1px solid #e5e7eb;">art. 6 ust. 1 lit. a – zgoda osoby, której dane dotyczą</td></tr>
  </tbody>
</table>

<h2>4. Okres przechowywania danych</h2>
<ul>
  <li><strong>Dane zamówieniowe i transakcyjne</strong> – przez okres 5 lat od końca roku, w którym złożono zamówienie (wymogi wynikające z przepisów podatkowych i rachunkowych).</li>
  <li><strong>Dane konta użytkownika</strong> – do momentu usunięcia konta; po usunięciu konta dane są anonimizowane, z wyjątkiem danych niezbędnych do realizacji obowiązków prawnych.</li>
  <li><strong>Dane przetwarzane na podstawie zgody</strong> – do momentu cofnięcia zgody.</li>
  <li><strong>Dane przetwarzane w celu dochodzenia lub obrony roszczeń</strong> – do upływu okresu przedawnienia roszczeń (co do zasady 3 lub 6 lat – w zależności od rodzaju roszczenia).</li>
  <li><strong>Pliki cookies sesyjne</strong> – do zakończenia sesji przeglądarki; <strong>pliki cookies trwałe</strong> – nie dłużej niż 2 lata od ostatniej wizyty.</li>
</ul>

<h2>5. Odbiorcy danych</h2>
<p>Twoje dane mogą być udostępniane wyłącznie podmiotom, z których usług korzystamy w celu realizacji zamówień i obsługi Sklepu, m.in.:</p>
<ul>
  <li>dostawcy usług hostingowych i infrastruktury IT,</li>
  <li>operatorzy systemów płatności elektronicznych (np. Przelewy24, PayU, Tpay),</li>
  <li>firmy kurierskie i operatorzy sieci paczek (np. InPost, DPD, DHL),</li>
  <li>biura rachunkowe i kancelarie prawne (w zakresie wymaganym przepisami prawa),</li>
  <li>organy publiczne – wyłącznie na podstawie obowiązujących przepisów prawa i stosownych żądań.</li>
</ul>
<p>Administrator nie sprzedaje danych osobowych osobom trzecim ani nie udostępnia ich w celach reklamowych podmiotom zewnętrznym.</p>

<h2>6. Przekazywanie danych do państw trzecich</h2>
<p>Co do zasady dane osobowe przetwarzane są na terytorium Europejskiego Obszaru Gospodarczego (EOG). W przypadku korzystania z usług podmiotów spoza EOG (np. Google Analytics, Facebook Pixel – jeśli aktywne), przekazywanie danych odbywa się na podstawie standardowych klauzul umownych zatwierdzonych przez Komisję Europejską lub innych mechanizmów przewidzianych w RODO.</p>

<h2>7. Prawa osób, których dane dotyczą</h2>
<p>Przysługują Ci następujące prawa w związku z przetwarzaniem danych osobowych:</p>
<ul>
  <li><strong>Prawo dostępu</strong> (art. 15 RODO) – prawo do uzyskania informacji o przetwarzanych danych i kopii danych.</li>
  <li><strong>Prawo do sprostowania</strong> (art. 16 RODO) – prawo do żądania poprawienia nieprawidłowych lub uzupełnienia niekompletnych danych.</li>
  <li><strong>Prawo do usunięcia danych</strong> (art. 17 RODO) – „prawo do bycia zapomnianym", z zastrzeżeniem przypadków, gdy przetwarzanie jest wymagane przepisami prawa.</li>
  <li><strong>Prawo do ograniczenia przetwarzania</strong> (art. 18 RODO) – prawo do żądania ograniczenia przetwarzania danych w określonych przypadkach.</li>
  <li><strong>Prawo do przenoszenia danych</strong> (art. 20 RODO) – prawo do otrzymania danych w ustrukturyzowanym formacie.</li>
  <li><strong>Prawo do sprzeciwu</strong> (art. 21 RODO) – prawo do wniesienia sprzeciwu wobec przetwarzania danych na podstawie uzasadnionego interesu, w tym profilowania.</li>
  <li><strong>Prawo do cofnięcia zgody</strong> – w każdej chwili, bez wpływu na zgodność z prawem przetwarzania dokonanego przed jej cofnięciem.</li>
  <li><strong>Prawo do wniesienia skargi</strong> – do Prezesa Urzędu Ochrony Danych Osobowych (UODO), ul. Stawki 2, 00-193 Warszawa.</li>
</ul>
<p>Aby skorzystać z powyższych praw, skontaktuj się z Administratorem pod adresem: <strong>{shop_email}</strong>. Odpowiedź udzielana jest bez zbędnej zwłoki, nie później niż w ciągu 30 dni.</p>

<h2>8. Pliki cookies i podobne technologie</h2>
<ol>
  <li>Sklep stosuje pliki cookies oraz podobne technologie (local storage, session storage) w celu zapewnienia prawidłowego funkcjonowania Sklepu, zapamiętywania preferencji użytkownika oraz — za Twoją zgodą — celów analitycznych i marketingowych.</li>
  <li>Wyróżniamy następujące kategorie cookies:
    <ul>
      <li><strong>Niezbędne</strong> – konieczne do działania Sklepu (sesja, koszyk, CSRF) – nie wymagają zgody.</li>
      <li><strong>Funkcjonalne</strong> – zapamiętują preferencje użytkownika (np. waluta, język).</li>
      <li><strong>Analityczne</strong> – umożliwiają analizę ruchu (np. Google Analytics) – wymagają zgody.</li>
      <li><strong>Marketingowe</strong> – służą do wyświetlania spersonalizowanych reklam – wymagają zgody.</li>
    </ul>
  </li>
  <li>Zgody na poszczególne kategorie cookies możesz udzielić lub cofnąć w każdej chwili za pomocą ustawień przeglądarki.</li>
</ol>

<h2>9. Bezpieczeństwo danych</h2>
<p>Administrator stosuje odpowiednie środki techniczne i organizacyjne w celu ochrony danych osobowych przed nieuprawnionym dostępem, utratą lub zniszczeniem, w tym: szyfrowanie transmisji danych (protokół HTTPS/TLS), hashowanie haseł algorytmem bcrypt, kontrolę dostępu do systemów informatycznych oraz regularne aktualizacje oprogramowania.</p>

<h2>10. Profilowanie i zautomatyzowane podejmowanie decyzji</h2>
<p>Administrator może dokonywać profilowania w celu personalizacji oferty (np. rekomendacje produktów, program lojalnościowy). Profilowanie to nie prowadzi do zautomatyzowanego podejmowania decyzji wywołujących skutki prawne dla Klienta w rozumieniu art. 22 RODO. Klientowi przysługuje prawo do sprzeciwu wobec profilowania na podstawie art. 21 RODO.</p>

<h2>11. Zmiany Polityki Prywatności</h2>
<p>Administrator zastrzega sobie prawo do zmiany niniejszej Polityki Prywatności w przypadku zmian przepisów prawa, wytycznych organów nadzorczych lub sposobu przetwarzania danych. O istotnych zmianach Klienci posiadający Konto zostaną powiadomieni drogą elektroniczną z co najmniej 14-dniowym wyprzedzeniem. Aktualna wersja Polityki jest zawsze dostępna w Sklepie.</p>
<p>Niniejsza Polityka Prywatności obowiązuje od dnia 1 stycznia 2026 r.</p>
HTML, 'text');
        $seed('shipping_content', <<<'HTML'
<h1>Dostawa i płatności</h1>
<p style="color:#6b7280;font-size:0.9em;">Aktualne informacje o kosztach i metodach dostawy oraz dostępnych formach płatności.</p>

<hr>

<h2>1. Czas realizacji zamówienia</h2>
<p>Czas realizacji to czas od momentu zaksięgowania płatności (lub złożenia zamówienia w przypadku płatności za pobraniem) do momentu przekazania paczki kurierowi.</p>
<table style="width:100%;border-collapse:collapse;font-size:0.9em;">
  <thead>
    <tr style="background:#f3f4f6;">
      <th style="text-align:left;padding:8px;border:1px solid #e5e7eb;">Moment złożenia zamówienia</th>
      <th style="text-align:left;padding:8px;border:1px solid #e5e7eb;">Nadanie przesyłki</th>
    </tr>
  </thead>
  <tbody>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;">Dzień roboczy, do godz. 14:00</td><td style="padding:8px;border:1px solid #e5e7eb;">Ten sam dzień</td></tr>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;">Dzień roboczy, po godz. 14:00</td><td style="padding:8px;border:1px solid #e5e7eb;">Następny dzień roboczy</td></tr>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;">Weekend lub dzień ustawowo wolny</td><td style="padding:8px;border:1px solid #e5e7eb;">Pierwszy kolejny dzień roboczy</td></tr>
  </tbody>
</table>
<p>W przypadku produktów dostępnych na zamówienie lub wykonywanych na indywidualne zlecenie czas realizacji podany jest w opisie produktu.</p>

<h2>2. Metody dostawy i koszty</h2>
<p>Aktualne opcje dostawy i ich koszty wyświetlane są w koszyku podczas składania zamówienia. Przykładowe dostępne metody:</p>
<ul>
  <li><strong>Kurier (DPD / DHL / InPost Kurier)</strong> – dostawa na wskazany adres w ciągu 1–2 dni roboczych od nadania.</li>
  <li><strong>Paczkomat InPost</strong> – odbiór w wybranym paczkomacie w ciągu 1–2 dni roboczych od nadania.</li>
  <li><strong>Odbiór osobisty</strong> – pod adresem: {shop_address}, w godzinach uzgodnionych ze Sprzedawcą.</li>
</ul>
<p>Przy zamówieniach powyżej określonego progu wartości dostawa jest bezpłatna — aktualny próg darmowej dostawy widoczny jest w koszyku oraz w banerze na stronie głównej Sklepu.</p>

<h2>3. Śledzenie przesyłki</h2>
<p>Po nadaniu paczki Klient otrzymuje na adres e-mail numer przesyłki wraz z linkiem do śledzenia na stronie przewoźnika. Status zamówienia można również sprawdzić w zakładce <em>Moje zamówienia</em> w koncie Klienta.</p>

<h2>4. Dostawa za granicę</h2>
<p>Sklep realizuje wysyłkę do wybranych krajów Unii Europejskiej. Jeśli przy wybranym produkcie nie wskazano inaczej, dostawa zagraniczna jest możliwa — jej koszt i czas są podawane podczas składania zamówienia. Sprzedawca nie ponosi odpowiedzialności za opóźnienia wynikające z odpraw celnych.</p>

<h2>5. Formy płatności</h2>
<table style="width:100%;border-collapse:collapse;font-size:0.9em;">
  <thead>
    <tr style="background:#f3f4f6;">
      <th style="text-align:left;padding:8px;border:1px solid #e5e7eb;">Metoda płatności</th>
      <th style="text-align:left;padding:8px;border:1px solid #e5e7eb;">Opis</th>
    </tr>
  </thead>
  <tbody>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;"><strong>BLIK</strong></td><td style="padding:8px;border:1px solid #e5e7eb;">Szybka płatność kodem BLIK – środki rezerwowane natychmiast.</td></tr>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;"><strong>Karta płatnicza (Visa / Mastercard)</strong></td><td style="padding:8px;border:1px solid #e5e7eb;">Bezpieczna transakcja 3D Secure. Dane karty nie są przechowywane przez Sklep.</td></tr>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;"><strong>Przelew online (Pay By Link)</strong></td><td style="padding:8px;border:1px solid #e5e7eb;">Szybki przelew przez stronę banku – płatność zaksięgowana w kilka minut.</td></tr>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;"><strong>Przelew tradycyjny</strong></td><td style="padding:8px;border:1px solid #e5e7eb;">Na podstawie danych do przelewu podanych po złożeniu zamówienia. Realizacja po zaksięgowaniu wpłaty (1–2 dni robocze).</td></tr>
    <tr><td style="padding:8px;border:1px solid #e5e7eb;"><strong>Płatność za pobraniem</strong></td><td style="padding:8px;border:1px solid #e5e7eb;">Gotówką lub kartą przy odbiorze paczki od kuriera (jeśli opcja jest dostępna).</td></tr>
  </tbody>
</table>
<p>Wszystkie transakcje elektroniczne realizowane są za pośrednictwem certyfikowanych operatorów płatności. Połączenie szyfrowane jest protokołem TLS.</p>

<h2>6. Faktury VAT</h2>
<p>Na życzenie Klienta wystawiamy fakturę VAT. Aby otrzymać fakturę, należy zaznaczyć odpowiednią opcję podczas składania zamówienia i podać dane firmowe (NIP, nazwa, adres). Faktura przesyłana jest w formie elektronicznej (PDF) na adres e-mail Klienta.</p>

<h2>7. Kontakt w sprawie dostawy</h2>
<p>W razie pytań dotyczących dostawy lub płatności prosimy o kontakt:<br>
📧 {shop_email}<br>
📞 {shop_phone}</p>
HTML, 'text');
        $seed('returns_content', <<<'HTML'
<h1>Zwroty i reklamacje</h1>
<p style="color:#6b7280;font-size:0.9em;">Twoje prawa jako Konsumenta są dla nas priorytetem.</p>

<hr>

<h2>1. Prawo do odstąpienia od umowy (zwrot towaru)</h2>
<p>Zgodnie z art. 27 ustawy z dnia 30 maja 2014 r. o prawach konsumenta (Dz.U. 2014 poz. 827 ze zm.), Konsument ma prawo odstąpić od umowy zawartej na odległość <strong>bez podania przyczyny</strong> w terminie <strong>14 dni</strong> od daty otrzymania towaru.</p>

<h3>Jak złożyć zwrot – krok po kroku:</h3>
<ol>
  <li><strong>Poinformuj nas</strong> – wyślij wiadomość e-mail na adres <strong>{shop_email}</strong> lub skontaktuj się telefonicznie pod numerem <strong>{shop_phone}</strong>, podając numer zamówienia i informację o chęci zwrotu.</li>
  <li><strong>Zapakuj towar</strong> – ostrożnie zapakuj produkt (najlepiej w oryginalne opakowanie), dołącz dowód zakupu (paragon lub fakturę).</li>
  <li><strong>Wyślij paczkę</strong> – prześlij towar na adres: <strong>{shop_address}</strong>. Bezpośredni koszt zwrotu (koszt odesłania) ponosi Konsument, o ile Sprzedawca nie postanowił inaczej.</li>
  <li><strong>Zwrot środków</strong> – po otrzymaniu zwracanego towaru i stwierdzeniu jego stanu, Sprzedawca zwraca wszystkie dokonane płatności (w tym koszt najtańszej dostępnej dostawy) w terminie <strong>14 dni</strong>.</li>
</ol>

<h3>Ważne informacje o zwrotach:</h3>
<ul>
  <li>Towar nie może nosić śladów użytkowania wykraczającego poza normalne czynności sprawdzające (jak w sklepie stacjonarnym).</li>
  <li>Prawo zwrotu <strong>nie przysługuje</strong> w przypadku: produktów wykonanych na indywidualne zamówienie; produktów z zapieczętowanym opakowaniem, których opakowanie zostało otwarte (ze względów higienicznych lub ochrony zdrowia); produktów cyfrowych dostarczonych po uruchomieniu.</li>
  <li>Zwrot środków realizowany jest tą samą metodą płatności, którą Klient dokonał zakupu, chyba że wyraźnie zgodził się na inny sposób.</li>
</ul>

<h2>2. Reklamacja z tytułu rękojmi (wada towaru)</h2>
<p>Na podstawie art. 556 i następnych Kodeksu cywilnego Sprzedawca ponosi odpowiedzialność za wady fizyczne i prawne sprzedanego towaru przez okres <strong>2 lat</strong> od daty jego wydania Klientowi.</p>

<h3>Kiedy przysługuje reklamacja?</h3>
<ul>
  <li>Produkt jest niezgodny z opisem lub zdjęciami w Sklepie.</li>
  <li>Produkt ma wadę fizyczną (uszkodzenie mechaniczne, wada materiałowa, nieprawidłowe działanie).</li>
  <li>Produkt jest niekompletny (brakuje elementów wchodzących w skład zestawu).</li>
  <li>Produkt był uszkodzony w trakcie transportu (zalecamy sporządzenie protokołu szkody przy kurierze).</li>
</ul>

<h3>Jak złożyć reklamację:</h3>
<p>Reklamację należy złożyć drogą elektroniczną na adres <strong>{shop_email}</strong> lub pisemnie na adres: <strong>{shop_address}</strong>.</p>
<p>Reklamacja powinna zawierać:</p>
<ul>
  <li>imię i nazwisko Klienta,</li>
  <li>numer zamówienia oraz datę zakupu,</li>
  <li>opis stwierdzonej wady (mile widziane zdjęcia),</li>
  <li>żądanie Klienta: naprawa / wymiana na nowy / obniżenie ceny / odstąpienie od umowy.</li>
</ul>
<p>Sprzedawca rozpatruje reklamację w terminie <strong>14 dni kalendarzowych</strong> od dnia jej otrzymania i informuje Klienta o sposobie jej rozpatrzenia drogą elektroniczną lub pisemnie.</p>

<h2>3. Gwarancja producenta</h2>
<p>Wybrane produkty mogą być objęte gwarancją producenta. Warunki gwarancji oraz dane producenta/gwaranta podawane są w opisie produktu lub w dołączonej karcie gwarancyjnej. Gwarancja producenta nie wyłącza, nie ogranicza ani nie zawiesza uprawnień Konsumenta z tytułu rękojmi.</p>

<h2>4. Pozasądowe rozwiązywanie sporów</h2>
<p>Konsumentowi przysługuje prawo do skorzystania z pozasądowych metod rozpatrywania reklamacji i dochodzenia roszczeń:</p>
<ul>
  <li>mediacja prowadzona przez właściwy Wojewódzki Inspektorat Inspekcji Handlowej,</li>
  <li>platforma ODR (Online Dispute Resolution) dostępna pod adresem: <a href="https://ec.europa.eu/consumers/odr" target="_blank">ec.europa.eu/consumers/odr</a>,</li>
  <li>więcej informacji na stronie <a href="https://www.uokik.gov.pl" target="_blank">uokik.gov.pl</a>.</li>
</ul>

<h2>5. Kontakt w sprawie zwrotów i reklamacji</h2>
<p>📧 {shop_email}<br>
📞 {shop_phone}<br>
📮 {shop_address}</p>
HTML, 'text');
        $seed('faq_content', <<<'HTML'
<h1>Najczęściej zadawane pytania (FAQ)</h1>
<p style="color:#6b7280;font-size:0.9em;">Odpowiedzi na najczęstsze pytania naszych Klientów.</p>

<hr>

<h2>Zamówienia</h2>

<h3>Jak złożyć zamówienie?</h3>
<p>Wybierz interesujące Cię produkty i dodaj je do koszyka (przycisk „Dodaj do koszyka"). Następnie przejdź do koszyka, sprawdź zawartość i kliknij „Przejdź do kasy". Wypełnij dane dostawy, wybierz metodę dostawy i formę płatności, a następnie potwierdź zamówienie. Na podany adres e-mail otrzymasz potwierdzenie złożenia zamówienia.</p>

<h3>Czy mogę złożyć zamówienie bez rejestracji?</h3>
<p>Tak, umożliwiamy zakupy jako gość — bez konieczności tworzenia konta. Rejestracja jest opcjonalna, jednak posiadanie konta daje dostęp do historii zamówień, szybszego składania kolejnych zamówień oraz programu lojalnościowego.</p>

<h3>Jak sprawdzić status mojego zamówienia?</h3>
<p>Status zamówienia możesz śledzić na dwa sposoby: w zakładce <em>Moje zamówienia</em> po zalogowaniu na konto lub korzystając z linku do śledzenia przesyłki, który otrzymasz w e-mailu potwierdzającym wysyłkę.</p>

<h3>Czy mogę zmienić lub anulować zamówienie?</h3>
<p>Zmiana lub anulowanie zamówienia jest możliwe wyłącznie przed jego przekazaniem do wysyłki. Skontaktuj się z nami jak najszybciej po złożeniu zamówienia: <strong>{shop_email}</strong> lub <strong>{shop_phone}</strong>. Po nadaniu paczki zmiany nie są możliwe — możesz natomiast skorzystać z prawa do zwrotu po otrzymaniu towaru.</p>

<h3>Czy mogę zamówić produkt, który jest chwilowo niedostępny?</h3>
<p>W przypadku produktów chwilowo niedostępnych możesz skorzystać z funkcji „Powiadom mnie o dostępności" (jeśli jest aktywna przy produkcie) lub skontaktować się z nami bezpośrednio — podamy szacowany termin uzupełnienia stanu magazynowego.</p>

<h2>Płatności</h2>

<h3>Jakie formy płatności są dostępne?</h3>
<p>Akceptujemy: BLIK, kartę płatniczą (Visa, Mastercard), szybki przelew online (Pay By Link), przelew tradycyjny oraz — w wybranych przypadkach — płatność za pobraniem przy odbiorze. Szczegóły znajdziesz w zakładce <strong>Dostawa i płatności</strong>.</p>

<h3>Czy moje dane płatnicze są bezpieczne?</h3>
<p>Tak. Wszystkie transakcje realizowane są za pośrednictwem certyfikowanych operatorów płatności (Przelewy24, PayU lub Tpay). Sklep nie przechowuje danych Twojej karty płatniczej — są one obsługiwane wyłącznie przez operatora płatności zgodnie z normą PCI DSS. Połączenie szyfrowane jest protokołem TLS.</p>

<h3>Kiedy zostanie naliczona płatność?</h3>
<p>W przypadku płatności online (BLIK, karta, przelew) środki są pobierane w momencie składania zamówienia. W przypadku przelewu tradycyjnego — realizacja zamówienia następuje po zaksięgowaniu wpłaty (zwykle 1–2 dni robocze).</p>

<h3>Czy mogę otrzymać fakturę VAT?</h3>
<p>Tak. Podczas składania zamówienia zaznacz opcję „Chcę fakturę VAT" i podaj dane firmowe (NIP, pełna nazwa, adres). Faktura zostanie wystawiona i przesłana w formie elektronicznej (PDF) na Twój adres e-mail.</p>

<h2>Dostawa</h2>

<h3>Kiedy zostanie wysłane moje zamówienie?</h3>
<p>Zamówienia złożone w dni robocze do godz. 14:00 wysyłamy tego samego dnia. W pozostałych przypadkach — następnego dnia roboczego. Po nadaniu paczki otrzymasz e-mail z numerem przesyłki i linkiem do śledzenia.</p>

<h3>Ile kosztuje dostawa?</h3>
<p>Koszty dostawy wyświetlane są w koszyku podczas składania zamówienia i zależą od wybranej metody wysyłki. Przy zamówieniach powyżej określonego progu dostawa jest bezpłatna — aktualny próg widoczny jest w banerze na stronie głównej.</p>

<h3>Co zrobić, jeśli paczka jest uszkodzona?</h3>
<p>Jeśli zauważysz uszkodzenia opakowania podczas odbioru od kuriera, sporządź protokół szkody w obecności kuriera — znacznie ułatwi to późniejszą reklamację. Następnie skontaktuj się z nami: <strong>{shop_email}</strong>.</p>

<h2>Zwroty i reklamacje</h2>

<h3>Ile mam czasu na zwrot towaru?</h3>
<p>Jako Konsument masz <strong>14 dni</strong> od daty otrzymania towaru na odstąpienie od umowy bez podania przyczyny. Szczegółowe informacje znajdziesz w zakładce <strong>Zwroty i reklamacje</strong>.</p>

<h3>Jak długo trwa rozpatrzenie reklamacji?</h3>
<p>Reklamacje rozpatrujemy w terminie <strong>14 dni kalendarzowych</strong> od dnia otrzymania zgłoszenia. O wyniku poinformujemy Cię drogą elektroniczną.</p>

<h3>Kiedy otrzymam zwrot pieniędzy?</h3>
<p>Zwrot środków realizujemy w terminie <strong>14 dni</strong> od otrzymania zwróconego towaru lub oświadczenia o odstąpieniu od umowy (jeśli zwrot towaru nastąpi później). Środki przekazywane są tą samą metodą płatności, której użyto przy zakupie.</p>

<h2>Konto i program lojalnościowy</h2>

<h3>Jak założyć konto?</h3>
<p>Kliknij „Zaloguj się / Zarejestruj" w prawym górnym rogu strony, wybierz „Utwórz konto" i wypełnij formularz rejestracyjny. Na podany adres e-mail zostanie wysłany link aktywacyjny.</p>

<h3>Zapomniałem/-am hasła — co zrobić?</h3>
<p>Kliknij „Zaloguj się", następnie „Zapomniałem/-am hasła" i podaj adres e-mail powiązany z kontem. Na ten adres wyślemy link do resetowania hasła.</p>

<h3>Jak działa program lojalnościowy?</h3>
<p>Za każdy złoty wydany w Sklepie otrzymujesz punkty lojalnościowe, które możesz wymieniać na zniżki przy kolejnych zakupach. Szczegóły programu dostępne są po zalogowaniu w zakładce <em>Moje konto → Program lojalnościowy</em>.</p>

<h2>Kontakt</h2>
<p>Nie znalazłeś/-aś odpowiedzi na swoje pytanie? Skontaktuj się z nami:<br>
📧 <strong>{shop_email}</strong><br>
📞 <strong>{shop_phone}</strong></p>
HTML, 'text');
        $seed('about_text',
            'Witamy w sklepie ' . $shopName . '! '
            . 'Oferujemy starannie dobrane produkty w atrakcyjnych cenach. '
            . 'Zamów online — szybka wysyłka lub odbiór osobisty. Zapraszamy!'
        );
    }

    private function seedDefaultRolePermissions(): void
    {
        $defaults = RolePermissionsController::DEFAULTS;

        foreach ($defaults as $role => $permissions) {
            foreach ($permissions as $permission) {
                RolePermission::firstOrCreate(
                    ['role' => $role, 'permission' => $permission]
                );
            }
        }
    }

    public function activate(Tenant $tenant)
    {
        $tenant->update(['status' => 'active']);

        return back()->with('success', "Sklep '{$tenant->name}' został aktywowany!");
    }

    public function suspend(Tenant $tenant)
    {
        $tenant->update(['status' => 'suspended']);

        return back()->with('success', "Sklep '{$tenant->name}' został zawieszony!");
    }

    /**
     * Truncate the tenant's cache table — useful after configuration changes
     * or when the tenant reports stale data.
     */
    public function clearCache(Tenant $tenant)
    {
        tenancy()->initialize($tenant);
        DB::table('cache')->truncate();
        tenancy()->end();

        return back()->with('success', 'Cache sklepu "' . $tenant->name . '" został wyczyszczony.');
    }

    /**
     * Generate impersonation token and redirect to tenant's manager panel.
     */
    public function impersonate(Tenant $tenant)
    {
        // Find first manager user in the tenant's DB
        tenancy()->initialize($tenant);
        $manager = User::where('role', 'manager')->first();
        tenancy()->end();

        if (!$manager) {
            return back()->withErrors(['error' => 'Brak konta managera w tym sklepie.']);
        }

        // Generate short-lived token stored in cache (5 minutes)
        $token = Str::random(40);
        // Use file store explicitly to bypass CacheTenancyBootstrapper (database store doesn't support tags)
        Cache::store('file')->put('impersonate:' . $token, [
            'tenant_id' => $tenant->id,
            'user_id' => $manager->id,
        ], now()->addMinutes(5));

        $parsed = parse_url(config('app.url', 'http://localhost'));
        $scheme = app()->environment('production') ? 'https' : ($parsed['scheme'] ?? 'http');
        $baseDomain = config('tenancy.base_domain');
        $port = isset($parsed['port']) ? ':' . $parsed['port'] : '';
        $targetUrl = $scheme . '://' . $tenant->subdomain . '.' . $baseDomain . $port . '/manager/impersonate?token=' . $token;

        return redirect()->away($targetUrl);
    }
}
